### PR TITLE
Fixes UTF8 chars being stripped from SOLR

### PR DESCRIPTION
**Pull request by lucygeneric**

### CODE REVIEW

**Comment by jonathanhoskin** [comment]
😎

**Comment by ryanwilliams** [comment]
HACKS!

**Comment by lucygeneric** [comment]
aw_yeah

**Comment by alagos** [comment]
For the record, but it looks like the issue this PR addressed was solved time ago [in this PR](https://github.com/sunspot/sunspot/pull/886).
So maybe it's safe to stop using this fork when the gem be updated, but it needs to be tested anyway.

**Pull request merged**
